name: Python application

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 8 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout actions
    - uses: actions/checkout@v1

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: wget
      uses: wei/wget@v1
      with:
        args: https://opensheet.elk.sh/1xZUXsnGFm34PZX_K5VUkYEsmm1AC6_QKOENdUHbsVpc/Origin -O /root/netflix.json --no-check-certificate
        
    - name: Update rank
      run: |
        cd script
        python nf_rank.py
    - name: commit
      run: |
        git config --global user.email haruka@dy.ax
        git config --global user.name DyAxy
        git add .
        git commit -m "update" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
